# =========================================
# RustFS Service
#
# Requires:
# - Docker Engine 20.10+
# =========================================

networks:
  # Reverse proxy network
  proxy-net:
    name: proxy-net
    external: true

volumes:
  rustfs-data-vol:
    name: rustfs-data-vol
    external: true

  rustfs-logs-vol:
    name: rustfs-logs-vol
    external: true

services:
  rustfs:
    image: rustfs/rustfs:latest
    environment:
      - RUSTFS_VOLUMES=/data/rustfs
      - RUSTFS_ADDRESS=0.0.0.0:9000
      - RUSTFS_CONSOLE_ENABLED=true
      - RUSTFS_CONSOLE_ADDRESS=0.0.0.0:9001
      # - RUSTFS_EXTERNAL_ADDRESS=:9000 # Same as internal since no port mapping
      # - RUSTFS_CORS_ALLOWED_ORIGINS=*
      # - RUSTFS_CONSOLE_CORS_ALLOWED_ORIGINS=*
      - RUSTFS_SERVER_DOMAINS=${DOMAIN}
      - RUSTFS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
      - RUSTFS_SECRET_KEY=${AWS_SECRET_ACCESS_KEY}
      # - RUSTFS_TLS_PATH=/opt/tls
      - RUSTFS_OBS_LOGGER_LEVEL=info
      - RUSTFS_OBS_LOG_DIRECTORY=/logs
      # - RUSTFS_OBS_ENDPOINT=http://otel-collector:4317
    # Labels for Traefik proxy
    # labels:
    #   - traefik.enable=true
    #   - traefik.http.routers.rustfs.entrypoints=websecure
    #   - traefik.http.routers.rustfs.rule=Host(`*.${DOMAIN}`)
    #   - traefik.http.routers.rustfs.service=rustfs
    #   - traefik.http.routers.rustfs.tls=true
    #   - traefik.http.routers.rustfs.tls.certresolver=le
    #   - traefik.http.routers.rustfs.tls.domains[0].main=${DOMAIN}
    #   - traefik.http.routers.rustfs.tls.domains[0].sans=*.${DOMAIN}
    #   - traefik.http.routers.rustfs.priority=11
    #   - traefik.http.services.rustfs.loadbalancer.server.port=9000
    #   - traefik.http.services.rustfs.loadbalancer.server.scheme=http
    #   - traefik.http.services.rustfs.loadbalancer.passHostHeader=true
    #   - traefik.http.routers.rustfs-adm.entrypoints=websecure
    #   - traefik.http.routers.rustfs-adm.rule=Host(`rustfs.${DOMAIN}`)
    #   - traefik.http.routers.rustfs-adm.service=rustfs-adm
    #   - traefik.http.routers.rustfs-adm.tls=true
    #   - traefik.http.routers.rustfs-adm.tls.certresolver=le
    #   - traefik.http.routers.rustfs-adm.tls.domains[0].main=${DOMAIN}
    #   - traefik.http.routers.rustfs-adm.tls.domains[0].sans=*.${DOMAIN}
    #   - traefik.http.routers.rustfs-adm.priority=10
    #   - traefik.http.services.rustfs-adm.loadbalancer.server.port=9001
    #   - traefik.http.services.rustfs-adm.loadbalancer.server.scheme=http
    #   - traefik.http.services.rustfs-adm.loadbalancer.passHostHeader=true
    networks:
      - proxy-net
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    volumes:
      - rustfs-data-vol:/data
      - rustfs-logs-vol:/logs
      # - ./certs:/opt/tls
    security_opt:
      - no-new-privileges:true
    # healthcheck:
    #   test: ['CMD', 'sh', '-c', 'curl -f http://localhost:9000/health']
    #   start_period: 20s
    #   interval: 5s
    #   retries: 5
    #   timeout: 4s
