# =========================================
# n8n.io
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

networks:
  # Network for connectting to databases
  database-net:
    name: database-net
    external: true
  # Network for connectting to proxy server
  proxy-net:
    name: reverse-proxy
    external: true


volumes:
  # Data volume
  n8n-data:
    name: n8n-data-vol

services:
  n8n:
    image: docker.io/n8nio/n8n:1.92.2
    environment:
      # https://docs.n8n.io/hosting/configuration/environment-variables/deployment/
      - N8N_HOST=${DOMAIN:?Variable not set}
      - N8N_PROTOCOL=https
      - N8N_ENCRYPTION_KEY=${ENCRYPTION_KEY}
      # https://docs.n8n.io/hosting/configuration/environment-variables/database/
      - DB_TYPE=postgresdb  # sqlite, postgresdb, mysqldb, mariadb
      - DB_TABLE_PREFIX=n8n_
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_SCHEMA=public
      # https://docs.n8n.io/hosting/configuration/environment-variables/timezone-localization/
      - TZ=UTC
      - GENERIC_TIMEZONE=UTC
      - N8N_DEFAULT_LOCALE=en
      # https://docs.n8n.io/hosting/configuration/environment-variables/logs/
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=console
      - DB_LOGGING_ENABLED=true
      - DB_LOGGING_OPTIONS=error
      # https://docs.n8n.io/hosting/configuration/environment-variables/user-management-smtp-2fa/
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=${SMTP_HOST}
      - N8N_SMTP_PORT=${SMTP_PORT}
      - N8N_SMTP_USER=${SMTP_USER}
      - N8N_SMTP_PASS=${SMTP_PASSWORD}
      - N8N_SMTP_SENDER=${SMTP_SENDER}
      - N8N_SMTP_SSL=true
      - N8N_MFA_ENABLED=true
      - N8N_USER_MANAGEMENT_JWT_SECRET=${JWT_SECRET:?Variable not set}
      # https://docs.n8n.io/hosting/configuration/environment-variables/endpoints/
      - WEBHOOK_URL=https://${DOMAIN:?Variable not set}
      - N8N_METRICS=true
      - N8N_METRICS_PREFIX=n8n_
      # https://docs.n8n.io/hosting/configuration/environment-variables/workflows/
      - N8N_WORKFLOW_ACTIVATION_BATCH_SIZE=2

      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    # labels:
    #   # Labels for Traefik proxy
    #   - traefik.enable=true
    #   - traefik.constraint-label=traefik-public
    #   - traefik.http.routers.n8n.entrypoints=websecure
    #   - traefik.http.routers.n8n.rule=Host(`${DOMAIN:?Variable not set}`)
    #   - traefik.http.routers.n8n.service=n8n
    #   - traefik.http.routers.n8n.priority=12
    #   - traefik.http.middlewares.n8n.headers.SSLRedirect=true
    #   - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
    #   - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
    #   - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
    #   - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
    #   - traefik.http.middlewares.n8n.headers.SSLHost=${DOMAIN:?Variable not set}
    #   - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
    #   - traefik.http.middlewares.n8n.headers.STSPreload=true
    #   - traefik.http.routers.n8n.middlewares=n8n@docker
    #   - traefik.http.services.n8n.loadbalancer.server.port=5678
    networks:
      - database-net
      - proxy-net
    # ports:
    #   - 5678:5678
    restart: unless-stopped
