# =========================================
# Valkey (https://valkey.io) - Redis Fork for Open Source Forever
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

networks:
  redis-net:
    name: redis-net
    external: true

volumes:
  valkey-vol:
    name: valkey-vol
    external: true

services:
  valkey:
    image: valkey/valkey:9-alpine
    # command: ["valkey-server", "--save", "60", "1", "--loglevel", "warning"]
    networks:
      - redis-net
    # ports:
    #   - 6379:6379
    restart: unless-stopped
    volumes:
      - valkey-vol:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      start_period: 10s
      retries: 3
      timeout: 5s
      interval: 10s
