# =========================================
# PostgreSQL
#
# Requires:
# - Docker Engine 19.03.0+
# - Docker Compose 1.27.0+
# =========================================

networks:
  postgres-net:
    name: database-net
    external: true

volumes:
  postgres-vol:
    name: postgres-vol
    external: true

services:
  postgres:
    image: postgres:18-alpine
    environment:
      # - POSTGRES_INITDB_ARGS=
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - postgres-net
    # ports:
    #   - 5432:5432
    restart: unless-stopped
    stop_signal: SIGINT
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      start_period: 20s
      retries: 3
      timeout: 3s
      interval: 10s
