services:
  doku:
    image: amerkurev/doku:latest
    container_name: doku
    environment:
      # Server settings
      - HOST=0.0.0.0
      - PORT=9090
      - LOG_LEVEL=info
      - DEBUG=false
      - UVICORN_WORKERS=1
      # # Authentication settings
      # - BASIC_HTPASSWD=/.htpasswd
      # # SSL settings
      # - SSL_KEYFILE=/.ssl/key.pem
      # - SSL_CERTFILE=/.ssl/cert.pem
      # - SSL_CIPHERS=TLSv1
      # Docker settings
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DOCKER_VERSION=auto
      - DOCKER_TLS_VERIFY=false
      - DOCKER_CERT_PATH=
      - DOCKER_TIMEOUT=60
      - DOCKER_MAX_POOL_SIZE=10
      - DOCKER_USE_SSH_CLIENT=false
      # Scan settings
      - BINDMOUNT_IGNORE_PATTERNS=""
      - DISABLE_OVERLAY2_SCAN=false
      - SCAN_USE_DU=true
      - SCAN_INTERVAL=60
      - SCAN_LOGFILE_INTERVAL=300
      - SCAN_BINDMOUNTS_INTERVAL=3600
      - SCAN_OVERLAY2_INTERVAL=86400
      - SCAN_INTENSITY=normal
      # Unit settings
      - SI=true
    ports:
      - "9090:9090"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostroot:ro
      # - ./.htpasswd:/.htpasswd:ro
      # - ./ssl/cert.pem:/.ssl/cert.pem:ro
      # - ./ssl/key.pem:/.ssl/key.pem:ro
    restart: unless-stopped
